# Generated by Django 4.1 on 2022-10-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liker',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='post_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
